from .schema import (
    BaseConfig,
    PurchaseConfig,
    ActivityFundsConfig,
    PresentsConfig,
    AssignmentConfig,
    ContestConfig,
    ProduceConfig,
    MissionRewardConfig,
    ClubRewardConfig,
    UpgradeSupportCardConfig,
    CapsuleToysConfig,
    TraceConfig,
    StartGameConfig,
    EndGameConfig,
    MiscConfig,
    DailyMoneyShopItems,
    ProduceAction,
    Priority,
    RecommendCardDetectionMode,
    APShopItems,
    conf,
)

# 配置升级逻辑
from .upgrade import upgrade_config
from .migrations import MIGRATION_REGISTRY, LATEST_VERSION

__all__ = [
    # schema 导出
    "BaseConfig",
    "PurchaseConfig",
    "ActivityFundsConfig",
    "PresentsConfig",
    "AssignmentConfig",
    "ContestConfig",
    "ProduceConfig",
    "MissionRewardConfig",
    "ClubRewardConfig",
    "UpgradeSupportCardConfig",
    "CapsuleToysConfig",
    "TraceConfig",
    "StartGameConfig",
    "EndGameConfig",
    "MiscConfig",
    "DailyMoneyShopItems",
    "ProduceAction",
    "Priority",
    "RecommendCardDetectionMode",
    "APShopItems",
    "upgrade_config",
    "conf",
    "migrations",
    "MIGRATION_REGISTRY",
    "LATEST_VERSION",
]